### ISSUE TITLE
Cryptic error message when submitting signup twice

### ISSUE THREAD

**Issue by mebster** [nuvla/ui#350] opened 2020-04-08 09:42 UTC
![Capture d’écran, le 2020-04-08 à 11 40 39](https://user-images.githubusercontent.com/419519/78769728-025a2300-798e-11ea-9da3-201e1c301ca2.png)

**Comment by konstan** [comment] 2020-04-08 14:08
@mebster this is the duplicate of https://github.com/nuvla/ui/issues/321

**Closed** 2020-04-09 06:36 UTC
Labels: T5 Bug
