### ISSUE TITLE
broken link to "Full documentation at Nuvla Docs" on NB creation modal

### ISSUE THREAD

**Issue by konstan** [nuvla/ui#505] opened 2020-12-14 17:10 UTC
Page not found
https://docs.nuvla.io/docs/nuvlabox/nuvlabox-engine/quickstart.html

**Comment by konstan** [comment] 2021-02-12 13:56
Now I see that the link is missing completely, but the `Full documentation at` text is present.

![Screenshot 2021-02-12 at 14 54 19](https://user-images.githubusercontent.com/353767/107776890-7568be80-6d42-11eb-902c-047c0dc1f932.png)

**Comment by 0xbase12** [comment] 2021-02-12 14:35
I'm not able to reproduce. What is the version of the UI visible in the footer

**Comment by 0xbase12** [comment] 2021-02-12 15:12
Closing

**Closed by 0xbase12** 2021-02-12 15:12 UTC

**Comment by konstan** [comment] 2021-02-12 15:49
The problem was in my branch after merging from master - dictionary.cljs was missing `:nuvla-docs` key.
