### ISSUE TITLE
UX - connection between the playbooks and hostlevel management is not clear from the action names

### ISSUE THREAD

**Issue by konstan** [nuvla/ui#872] opened 2022-09-06 14:24 UTC
![Screenshot 2022-09-06 at 16 22 13](https://user-images.githubusercontent.com/353767/188660149-b9695ab0-b05a-4007-9108-8985d18295f7.png)

**Comment by MTrost** [comment] 2022-11-17 17:02
closed, duplicate of https://github.com/nuvla/ui/issues/874

**Closed** 2022-11-18 07:35 UTC
Labels: T3 Enhancement
