### ISSUE TITLE
don’t show intermediate fail msgs for mixed jobs that fail to push

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/ui#659] opened 2021-07-07 07:18 UTC
derived from https://github.com/nuvla/job-engine/issues/194

do not show an error message if jobs are in a QUEUED state

**Comment by 0xbase12** [comment] 2021-07-09 14:48
Job error message are showed only when they are in state ERROR.

Progress bar is red when last job is FAILED or Deployment is in Error state.

UI behavior is good. The issue should be fixed on job-engine.
When a job is in mixed mode and fail to push, the resource state should not be moved to Error state.
https://github.com/nuvla/job-engine/blob/f81136c7d5a238304775f4157ff31b3f7f103131/code/src/nuvla/job/actions/deployment_stop.py#L83

Progress bar is red and Deployment is Errored.

The issue is that the dep

**Closed** 2021-07-12 08:41 UTC
Labels: NB Testing Dojo 1
